//! The guns, generated from the game by `me_level/examples/weapondata.rs`: each TdSharedContent
//! weapon class's defaults merged down TdWeapon -> TdWeapon_Light / _Heavy -> the class, with
//! its [Weapons] config. Don't edit by hand; rerun the example.

use super::{Burst, WeaponClass};

pub static PISTOL_GLOCK18C: WeaponClass = WeaponClass {
    name: "TdWeapon_Pistol_Glock18c",
    package: "WP_Glock18",
    mesh: "SK_Glock18",
    anim_set_1p: "AS_C1P_OneHanded_Glock18",
    heavy: false,
    firing_state: "WeaponBursting",
    automatic_refire: false,
    burst_max: 3,
    pellets: 1,
    fire_interval: 0.1,
    damage: 17.0,
    momentum: 12.0,
    spread: 0.03,
    fall_off_distance: 600.0,
    weapon_range: 4500.0,
    death_anim_type: 4,
    max_ammo: 33,
    reload_time: 2.0,
    equip_time: 0.75,
    pose_profile: "OneHanded-Glock18",
    sniper_bullet: false,
    recoil_amount: 2.0,
    recoil_recover_time: 0.1,
    max_recoil: 9.0,
    kickback_amount: 10.0,
    combat_range_max: 2500.0,
    bursts: [Burst { length_min: 3, length_max: 3, pause_min: 0.5, pause_max: 1.0 }, Burst { length_min: 2, length_max: 3, pause_min: 1.0, pause_max: 1.2 }, Burst { length_min: 1, length_max: 2, pause_min: 1.0, pause_max: 1.5 }],
    pre_reload_time: 0.5,
    reload_ready_time: (2.5, 3.2),
    ai_damage_multiplier: 1.0,
    out_of_ammo_anim: "weaponposeempty",
    fire_1p: "A_WP_AutoPistol_Glock18c.Fire.Fire1P",
    fire_3p: "A_WP_AutoPistol_Glock18c.Fire.Fire3P",
    reverb_1p: "A_WP_AutoPistol_Glock18c.Reverb.Reverb1P",
    reverb_3p: "A_WP_AutoPistol_Glock18c.Reverb.Reverb3P",
    click: "A_WP_Handling.Pistol.DryFire",
    drop: "A_WP_Drops.1Handed.1HandedDrop",
    pickup: "A_WP_Handling.1Handed.1HandedHandling",
};

pub static PISTOL_COLT1911: WeaponClass = WeaponClass {
    name: "TdWeapon_Pistol_Colt1911",
    package: "WP_Colt1911",
    mesh: "SK_Colt1911",
    anim_set_1p: "AS_C1P_OneHanded_Colt1911",
    heavy: false,
    firing_state: "WeaponFiring",
    automatic_refire: false,
    burst_max: 1,
    pellets: 1,
    fire_interval: 0.2,
    damage: 42.0,
    momentum: 20.0,
    spread: 0.03,
    fall_off_distance: 600.0,
    weapon_range: 4500.0,
    death_anim_type: 4,
    max_ammo: 8,
    reload_time: 2.0,
    equip_time: 0.75,
    pose_profile: "OneHanded-Colt1911",
    sniper_bullet: false,
    recoil_amount: 2.0,
    recoil_recover_time: 0.1,
    max_recoil: 9.0,
    kickback_amount: 10.0,
    combat_range_max: 2000.0,
    bursts: [Burst { length_min: 1, length_max: 1, pause_min: 0.3, pause_max: 0.5 }, Burst { length_min: 1, length_max: 1, pause_min: 0.5, pause_max: 1.0 }, Burst { length_min: 1, length_max: 1, pause_min: 1.0, pause_max: 1.5 }],
    pre_reload_time: 0.5,
    reload_ready_time: (2.5, 3.2),
    ai_damage_multiplier: 1.0,
    out_of_ammo_anim: "weaponposeempty",
    fire_1p: "A_WP_Pistol_Colt1911.Fire.Fire1P",
    fire_3p: "A_WP_Pistol_Colt1911.Fire.Fire3P",
    reverb_1p: "A_WP_Pistol_Colt1911.Reverb.Reverb1P",
    reverb_3p: "A_WP_Pistol_Colt1911.Reverb.Reverb3P",
    click: "A_WP_Handling.Pistol.DryFire",
    drop: "A_WP_Drops.1Handed.1HandedDrop",
    pickup: "A_WP_Handling.1Handed.1HandedHandling",
};

pub static PISTOL_BERETTAM93R: WeaponClass = WeaponClass {
    name: "TdWeapon_Pistol_BerettaM93R",
    package: "WP_BerettaM93R",
    mesh: "SK_BerettaM93R",
    anim_set_1p: "AS_C1P_OneHanded_BerettaM93R",
    heavy: false,
    firing_state: "WeaponFiring",
    automatic_refire: true,
    burst_max: 3,
    pellets: 1,
    fire_interval: 0.1,
    damage: 19.0,
    momentum: 20.0,
    spread: 0.03,
    fall_off_distance: 600.0,
    weapon_range: 4500.0,
    death_anim_type: 10,
    max_ammo: 21,
    reload_time: 2.0,
    equip_time: 0.75,
    pose_profile: "OneHanded-BerettaM93R",
    sniper_bullet: false,
    recoil_amount: 0.5,
    recoil_recover_time: 0.1,
    max_recoil: 6.0,
    kickback_amount: 10.0,
    combat_range_max: 2500.0,
    bursts: [Burst { length_min: 6, length_max: 6, pause_min: 0.5, pause_max: 1.0 }, Burst { length_min: 3, length_max: 5, pause_min: 1.0, pause_max: 1.2 }, Burst { length_min: 2, length_max: 4, pause_min: 1.0, pause_max: 1.5 }],
    pre_reload_time: 0.0,
    reload_ready_time: (1.0, 1.0),
    ai_damage_multiplier: 1.0,
    out_of_ammo_anim: "",
    fire_1p: "A_WP_Pistol_BerettaM93R.Fire.Fire1P",
    fire_3p: "A_WP_Pistol_BerettaM93R.Fire.Fire3P",
    reverb_1p: "A_WP_Pistol_BerettaM93R.Reverb.Reverb1P",
    reverb_3p: "A_WP_Pistol_BerettaM93R.Reverb.Reverb3P",
    click: "A_WP_Handling.1Handed.DryFire",
    drop: "A_WP_Drops.1Handed.1HandedDrop",
    pickup: "A_WP_Handling.1Handed.1HandedHandling",
};

pub static SMG_STEYRTMP: WeaponClass = WeaponClass {
    name: "TdWeapon_SMG_SteyrTMP",
    package: "WP_SteyrTMP",
    mesh: "SK_SteyrTMP",
    anim_set_1p: "AS_C1P_OneHanded_SteyrTMP",
    heavy: false,
    firing_state: "WeaponFiring",
    automatic_refire: true,
    burst_max: 3,
    pellets: 1,
    fire_interval: 0.06,
    damage: 15.5,
    momentum: 20.0,
    spread: 0.008,
    fall_off_distance: 800.0,
    weapon_range: 3000.0,
    death_anim_type: 10,
    max_ammo: 30,
    reload_time: 3.25,
    equip_time: 0.75,
    pose_profile: "OneHanded-SteyrTMP",
    sniper_bullet: false,
    recoil_amount: 0.6,
    recoil_recover_time: 0.1,
    max_recoil: 6.0,
    kickback_amount: 10.0,
    combat_range_max: 3000.0,
    bursts: [Burst { length_min: 6, length_max: 6, pause_min: 0.5, pause_max: 1.0 }, Burst { length_min: 3, length_max: 5, pause_min: 0.5, pause_max: 1.0 }, Burst { length_min: 2, length_max: 5, pause_min: 1.0, pause_max: 2.0 }],
    pre_reload_time: 0.0,
    reload_ready_time: (1.0, 1.0),
    ai_damage_multiplier: 1.0,
    out_of_ammo_anim: "",
    fire_1p: "A_WP_MiniSMG_SteyrTMP.Fire.Fire1P",
    fire_3p: "A_WP_MiniSMG_SteyrTMP.Fire.Fire3P",
    reverb_1p: "A_WP_MiniSMG_SteyrTMP.Reverb.Reverb1P",
    reverb_3p: "A_WP_MiniSMG_SteyrTMP.Reverb.Reverb3P",
    click: "A_WP_Handling.1Handed.DryFire",
    drop: "A_WP_Drops.1Handed.1HandedDrop",
    pickup: "A_WP_Handling.1Handed.1HandedHandling",
};

pub static ASSAULTRIFLE_MP5K: WeaponClass = WeaponClass {
    name: "TdWeapon_AssaultRifle_MP5K",
    package: "WP_MP5K",
    mesh: "SK_MP5K",
    anim_set_1p: "AS_C1P_TwoHanded_MP5K",
    heavy: true,
    firing_state: "WeaponFiring",
    automatic_refire: true,
    burst_max: 30,
    pellets: 1,
    fire_interval: 0.1,
    damage: 25.0,
    momentum: 13.0,
    spread: 0.04,
    fall_off_distance: 2000.0,
    weapon_range: 8000.0,
    death_anim_type: 2,
    max_ammo: 30,
    reload_time: 3.4667,
    equip_time: 0.75,
    pose_profile: "TwoHanded-MP5K",
    sniper_bullet: false,
    recoil_amount: 0.8,
    recoil_recover_time: 0.1,
    max_recoil: 1.0,
    kickback_amount: 20.0,
    combat_range_max: 4000.0,
    bursts: [Burst { length_min: 6, length_max: 6, pause_min: 0.3, pause_max: 0.5 }, Burst { length_min: 3, length_max: 6, pause_min: 0.8, pause_max: 1.2 }, Burst { length_min: 2, length_max: 5, pause_min: 1.0, pause_max: 2.0 }],
    pre_reload_time: 0.5,
    reload_ready_time: (3.9, 4.2),
    ai_damage_multiplier: 1.0,
    out_of_ammo_anim: "",
    fire_1p: "A_WP_SMG_MP5K.Fire.Fire1P",
    fire_3p: "A_WP_SMG_MP5K.Fire.Fire3P",
    reverb_1p: "A_WP_SMG_MP5K.Reverb.Reverb1P",
    reverb_3p: "A_WP_SMG_MP5K.Reverb.Reverb3P",
    click: "A_WP_Handling.2Handed.DryFire",
    drop: "A_WP_Drops.2Handed.2HandedDrop",
    pickup: "A_WP_Handling.2Handed.2HandedHandling",
};

pub static ASSAULTRIFLE_FNSCARL: WeaponClass = WeaponClass {
    name: "TdWeapon_AssaultRifle_FNSCARL",
    package: "WP_FNSCARL",
    mesh: "SK_FNSCARL",
    anim_set_1p: "AS_C1P_TwoHanded_FNSCARL",
    heavy: true,
    firing_state: "WeaponFiring",
    automatic_refire: true,
    burst_max: 3,
    pellets: 1,
    fire_interval: 0.11,
    damage: 35.0,
    momentum: 20.0,
    spread: 0.02,
    fall_off_distance: 2000.0,
    weapon_range: 9000.0,
    death_anim_type: 2,
    max_ammo: 30,
    reload_time: 2.2,
    equip_time: 0.75,
    pose_profile: "TwoHanded-FNSCARL",
    sniper_bullet: false,
    recoil_amount: 0.8,
    recoil_recover_time: 0.1,
    max_recoil: 0.0,
    kickback_amount: 20.0,
    combat_range_max: 5000.0,
    bursts: [Burst { length_min: 6, length_max: 9, pause_min: 0.3, pause_max: 0.8 }, Burst { length_min: 3, length_max: 6, pause_min: 0.5, pause_max: 1.0 }, Burst { length_min: 2, length_max: 4, pause_min: 1.0, pause_max: 2.0 }],
    pre_reload_time: 0.5,
    reload_ready_time: (2.8, 3.2),
    ai_damage_multiplier: 1.0,
    out_of_ammo_anim: "",
    fire_1p: "A_WP_Assault_FNSCARL.Fire.Fire1P",
    fire_3p: "A_WP_Assault_FNSCARL.Fire.Fire3P",
    reverb_1p: "A_WP_Assault_FNSCARL.Reverb.Reverb1P",
    reverb_3p: "A_WP_Assault_FNSCARL.Reverb.Reverb3P",
    click: "A_WP_Handling.2Handed.DryFire",
    drop: "A_WP_Drops.2Handed.2HandedDrop",
    pickup: "A_WP_Handling.2Handed.2HandedHandling",
};

pub static ASSAULTRIFLE_HKG36: WeaponClass = WeaponClass {
    name: "TdWeapon_AssaultRifle_HKG36",
    package: "WP_G36C",
    mesh: "SK_G36C",
    anim_set_1p: "AS_C1P_TwoHanded_G36C",
    heavy: true,
    firing_state: "WeaponFiring",
    automatic_refire: true,
    burst_max: 3,
    pellets: 1,
    fire_interval: 0.085,
    damage: 30.0,
    momentum: 20.0,
    spread: 0.03,
    fall_off_distance: 2000.0,
    weapon_range: 9000.0,
    death_anim_type: 2,
    max_ammo: 30,
    reload_time: 3.5,
    equip_time: 0.75,
    pose_profile: "TwoHanded-G36C",
    sniper_bullet: false,
    recoil_amount: 0.8,
    recoil_recover_time: 0.1,
    max_recoil: 1.0,
    kickback_amount: 20.0,
    combat_range_max: 5000.0,
    bursts: [Burst { length_min: 6, length_max: 9, pause_min: 0.3, pause_max: 0.8 }, Burst { length_min: 3, length_max: 6, pause_min: 0.5, pause_max: 1.0 }, Burst { length_min: 2, length_max: 4, pause_min: 1.0, pause_max: 2.0 }],
    pre_reload_time: 0.0,
    reload_ready_time: (1.0, 1.0),
    ai_damage_multiplier: 1.0,
    out_of_ammo_anim: "",
    fire_1p: "A_WP_Assault_G36.Fire.Fire1P",
    fire_3p: "A_WP_Assault_G36.Fire.Fire3P",
    reverb_1p: "A_WP_Assault_G36.Reverb.Reverb1P",
    reverb_3p: "A_WP_Assault_G36.Reverb.Reverb3P",
    click: "A_WP_Handling.2Handed.DryFire",
    drop: "A_WP_Drops.2Handed.2HandedDrop",
    pickup: "A_WP_Handling.2Handed.2HandedHandling",
};

pub static MACHINEGUN_FNMINIMI: WeaponClass = WeaponClass {
    name: "TdWeapon_Machinegun_FNMinimi",
    package: "WP_FNMinimi",
    mesh: "SK_FNMinimi",
    anim_set_1p: "AS_C1P_TwoHanded_FNMinimi",
    heavy: true,
    firing_state: "WeaponFiring",
    automatic_refire: true,
    burst_max: 3,
    pellets: 1,
    fire_interval: 0.12,
    damage: 36.0,
    momentum: 20.0,
    spread: 0.04,
    fall_off_distance: 6000.0,
    weapon_range: 20000.0,
    death_anim_type: 5,
    max_ammo: 99,
    reload_time: 6.6,
    equip_time: 1.0,
    pose_profile: "TwoHanded-FNMinimi",
    sniper_bullet: false,
    recoil_amount: 1.0,
    recoil_recover_time: 0.1,
    max_recoil: 1.0,
    kickback_amount: 50.0,
    combat_range_max: 15000.0,
    bursts: [Burst { length_min: 15, length_max: 25, pause_min: 1.5, pause_max: 2.0 }, Burst { length_min: 15, length_max: 25, pause_min: 1.5, pause_max: 2.0 }, Burst { length_min: 20, length_max: 30, pause_min: 1.5, pause_max: 2.0 }],
    pre_reload_time: 0.5,
    reload_ready_time: (2.8, 3.2),
    ai_damage_multiplier: 1.0,
    out_of_ammo_anim: "",
    fire_1p: "A_WP_HeavyMG_FNMiniMe.Fire.Fire1P",
    fire_3p: "A_WP_HeavyMG_FNMiniMe.Fire.Fire3P",
    reverb_1p: "A_WP_HeavyMG_FNMiniMe.Reverb.Reverb1P",
    reverb_3p: "A_WP_HeavyMG_FNMiniMe.Reverb.Reverb3P",
    click: "A_WP_Handling.Heavy.DryFire",
    drop: "A_WP_Drops.Heavy.HeavyDrop",
    pickup: "A_WP_Handling.Heavy.HeavyHandling",
};

pub static SHOTGUN_REMINGTON870: WeaponClass = WeaponClass {
    name: "TdWeapon_Shotgun_Remington870",
    package: "WP_Remington870",
    mesh: "SK_Remington870",
    anim_set_1p: "AS_C1P_TwoHanded_Remington",
    heavy: true,
    firing_state: "WeaponFiring",
    automatic_refire: false,
    burst_max: 1,
    pellets: 10,
    fire_interval: 1.2,
    damage: 16.0,
    momentum: 28.0,
    spread: 0.12,
    fall_off_distance: 1500.0,
    weapon_range: 6000.0,
    death_anim_type: 3,
    max_ammo: 7,
    reload_time: 1.2667,
    equip_time: 1.2,
    pose_profile: "TwoHanded-Remington",
    sniper_bullet: false,
    recoil_amount: 3.0,
    recoil_recover_time: 0.1,
    max_recoil: 9.0,
    kickback_amount: 50.0,
    combat_range_max: 2000.0,
    bursts: [Burst { length_min: 1, length_max: 1, pause_min: 0.8, pause_max: 1.2 }, Burst { length_min: 1, length_max: 1, pause_min: 1.0, pause_max: 1.5 }, Burst { length_min: 1, length_max: 1, pause_min: 1.5, pause_max: 2.5 }],
    pre_reload_time: 1.5,
    reload_ready_time: (4.5, 5.5),
    ai_damage_multiplier: 1.0,
    out_of_ammo_anim: "",
    fire_1p: "A_WP_Shotgun_Remington870.Fire.Fire1P",
    fire_3p: "A_WP_Shotgun_Remington870.Fire.Fire3P",
    reverb_1p: "A_WP_Shotgun_Remington870.Reverb.Reverb1P",
    reverb_3p: "A_WP_Shotgun_Remington870.Reverb.Reverb3P",
    click: "A_WP_Handling.2Handed.DryFire",
    drop: "A_WP_Drops.2Handed.2HandedDrop",
    pickup: "A_WP_Handling.2Handed.2HandedHandling",
};

pub static SHOTGUN_NEOSTEAD: WeaponClass = WeaponClass {
    name: "TdWeapon_Shotgun_Neostead",
    package: "WP_Neostead",
    mesh: "SK_Neostead",
    anim_set_1p: "AS_C1P_TwoHanded_Neostead",
    heavy: true,
    firing_state: "WeaponFiring",
    automatic_refire: false,
    burst_max: 1,
    pellets: 10,
    fire_interval: 1.1,
    damage: 16.0,
    momentum: 30.0,
    spread: 0.1,
    fall_off_distance: 1500.0,
    weapon_range: 6000.0,
    death_anim_type: 3,
    max_ammo: 12,
    reload_time: 1.2667,
    equip_time: 1.2,
    pose_profile: "TwoHanded-Neostead",
    sniper_bullet: false,
    recoil_amount: 3.0,
    recoil_recover_time: 0.1,
    max_recoil: 9.0,
    kickback_amount: 50.0,
    combat_range_max: 4000.0,
    bursts: [Burst { length_min: 1, length_max: 1, pause_min: 0.6, pause_max: 0.8 }, Burst { length_min: 1, length_max: 1, pause_min: 0.8, pause_max: 1.2 }, Burst { length_min: 1, length_max: 1, pause_min: 1.5, pause_max: 2.0 }],
    pre_reload_time: 1.5,
    reload_ready_time: (5.9, 6.2),
    ai_damage_multiplier: 1.0,
    out_of_ammo_anim: "",
    fire_1p: "A_WP_Shotgun_Neostead.Fire.Fire1P",
    fire_3p: "A_WP_Shotgun_Neostead.Fire.Fire3P",
    reverb_1p: "A_WP_Shotgun_Neostead.Reverb.Reverb1P",
    reverb_3p: "A_WP_Shotgun_Neostead.Reverb.Reverb3P",
    click: "A_WP_Handling.2Handed.DryFire",
    drop: "A_WP_Drops.2Handed.2HandedDrop",
    pickup: "A_WP_Handling.2Handed.2HandedHandling",
};

pub static SNIPER_BARRETM95: WeaponClass = WeaponClass {
    name: "TdWeapon_Sniper_BarretM95",
    package: "WP_M95",
    mesh: "SK_M95",
    anim_set_1p: "AS_C1P_TwoHanded_M95",
    heavy: true,
    firing_state: "WeaponFiring",
    automatic_refire: false,
    burst_max: 1,
    pellets: 1,
    fire_interval: 1.7,
    damage: 100.0,
    momentum: 50.0,
    spread: 0.001,
    fall_off_distance: 180000.0,
    weapon_range: 20000.0,
    death_anim_type: 0,
    max_ammo: 20,
    reload_time: 4.0,
    equip_time: 0.75,
    pose_profile: "TwoHanded-M95",
    sniper_bullet: true,
    recoil_amount: 1.0,
    recoil_recover_time: 0.1,
    max_recoil: 6.0,
    kickback_amount: 10.0,
    combat_range_max: 20000.0,
    bursts: [Burst { length_min: 1, length_max: 1, pause_min: 2.5, pause_max: 2.5 }, Burst { length_min: 1, length_max: 1, pause_min: 2.5, pause_max: 2.5 }, Burst { length_min: 1, length_max: 1, pause_min: 2.5, pause_max: 2.5 }],
    pre_reload_time: 0.0,
    reload_ready_time: (4.5, 4.7),
    ai_damage_multiplier: 0.8,
    out_of_ammo_anim: "",
    fire_1p: "A_WP_Sniper_BarretM95.Fire.Fire1P",
    fire_3p: "A_WP_Sniper_BarretM95.Fire.Fire3P",
    reverb_1p: "A_WP_Sniper_BarretM95.Reverb.Reverb1P",
    reverb_3p: "A_WP_Sniper_BarretM95.Reverb.Reverb3P",
    click: "A_WP_Handling.2Handed.DryFire",
    drop: "A_WP_Drops.Heavy.HeavyDrop",
    pickup: "A_WP_Handling.Heavy.HeavyHandling",
};

/// Every gun, pistols first.
pub static WEAPONS: [&WeaponClass; 11] = [&PISTOL_GLOCK18C, &PISTOL_COLT1911, &PISTOL_BERETTAM93R, &SMG_STEYRTMP, &ASSAULTRIFLE_MP5K, &ASSAULTRIFLE_FNSCARL, &ASSAULTRIFLE_HKG36, &MACHINEGUN_FNMINIMI, &SHOTGUN_REMINGTON870, &SHOTGUN_NEOSTEAD, &SNIPER_BARRETM95];
